packages: []
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp
  - workerd
ignoredBuiltDependencies: []
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@4.20260519.1'
  - '@types/node@25.9.0'
allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false
  workerd: set this to true or false
